---
# yaml-language-server: $schema=https://raw.githubusercontent.com/scilus/nf-neuro/main/modules/meta-schema.json
name: "preproc_singleeddy"
description: Apply Eddy (and Topup if already run)
keywords:
  - BET
  - T1
  - eddy
tools:
  - "scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"
  - "FSL":
      description: "FSL Toolbox and Scilpy Toolbox"
      homepage: "https://fsl.fmrib.ox.ac.uk/fsl/fslwiki"
input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - anat:
      type: file
      description: Anat Nifti image
      pattern: "*.{nii,nii.gz}"


output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - mask:
      type: file
      description: mask brain-extracted
      pattern: "*__mask.{nii,nii.gz}"


authors:
  - "@EliseCos"